# alembic/script.py.mako — template for migration files
"""phase1_database_foundation

Revision ID: f2029e7b9acb
Revises: 0002
Create Date: 2026-10-05 02:02:58.481932

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2029e7b9acb'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('priority_weight', sa.Integer(), server_default='100', nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), server_default='30', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='3', nullable=False),
    sa.Column('cost_input_per_1k', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('cost_output_per_1k', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_providers_slug'), 'ai_providers', ['slug'], unique=True)
    op.create_table('webhook_events',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature', sa.String(length=500), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_external_id'), 'webhook_events', ['external_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_processed'), 'webhook_events', ['processed'], unique=False)
    op.create_index(op.f('ix_webhook_events_provider'), 'webhook_events', ['provider'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('active_skill_slug', sa.String(length=50), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_is_archived'), 'conversations', ['is_archived'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('payment_invoices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('crypto_amount', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('crypto_address', sa.Text(), nullable=True),
    sa.Column('payment_url', sa.Text(), nullable=True),
    sa.Column('qr_code_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webhook_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_invoices_external_invoice_id'), 'payment_invoices', ['external_invoice_id'], unique=True)
    op.create_index(op.f('ix_payment_invoices_idempotency_key'), 'payment_invoices', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payment_invoices_status'), 'payment_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_payment_invoices_user_id'), 'payment_invoices', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('referrer_user_id', sa.UUID(), nullable=False),
    sa.Column('referred_user_id', sa.UUID(), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=False),
    sa.Column('landing_page_url', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qualified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rewarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['referred_user_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=False)
    op.create_index(op.f('ix_referrals_referred_user_id'), 'referrals', ['referred_user_id'], unique=True)
    op.create_index(op.f('ix_referrals_referrer_user_id'), 'referrals', ['referrer_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_table('skills',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('max_tokens', sa.Integer(), server_default='4096', nullable=False),
    sa.Column('preferred_provider_id', sa.UUID(), nullable=True),
    sa.Column('fallback_provider_id', sa.UUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cost_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fallback_provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preferred_provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_fallback_provider_id'), 'skills', ['fallback_provider_id'], unique=False)
    op.create_index(op.f('ix_skills_is_premium'), 'skills', ['is_premium'], unique=False)
    op.create_index(op.f('ix_skills_is_public'), 'skills', ['is_public'], unique=False)
    op.create_index(op.f('ix_skills_preferred_provider_id'), 'skills', ['preferred_provider_id'], unique=False)
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('skill_slug', sa.String(length=50), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_credits', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_skill_slug'), 'messages', ['skill_slug'], unique=False)
    op.create_table('reward_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('referral_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_release_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_invoice_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reference_invoice_id'], ['payment_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_transactions_referral_id'), 'reward_transactions', ['referral_id'], unique=False)
    op.create_index(op.f('ix_reward_transactions_scheduled_release_at'), 'reward_transactions', ['scheduled_release_at'], unique=False)
    op.create_index(op.f('ix_reward_transactions_status'), 'reward_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_reward_transactions_user_id'), 'reward_transactions', ['user_id'], unique=False)
    op.create_table('skill_tools',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=50), nullable=False),
    sa.Column('tool_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_tools_skill_id'), 'skill_tools', ['skill_id'], unique=False)
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.add_column('credit_ledger', sa.Column('balance_after', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('credit_ledger', sa.Column('reference_type', sa.String(length=50), nullable=True))
    op.add_column('credit_ledger', sa.Column('reference_id', sa.UUID(), nullable=True))
    op.add_column('credit_ledger', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('credit_ledger', 'student_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('credit_ledger', 'request_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('credit_ledger', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_credit_ledger_idempotency_key'), table_name='credit_ledger')
    op.create_index(op.f('ix_credit_ledger_idempotency_key'), 'credit_ledger', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_credit_ledger_reference_id'), 'credit_ledger', ['reference_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_reference_type'), 'credit_ledger', ['reference_type'], unique=False)
    op.alter_column('deliverables', 'request_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('deliverables', 'student_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('deliverables', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('feature_configurations', 'active_prompt_version_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('feature_configurations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_feature_configurations_feature_key'), table_name='feature_configurations')
    op.create_index(op.f('ix_feature_configurations_feature_key'), 'feature_configurations', ['feature_key'], unique=True)
    op.alter_column('model_configurations', 'provider_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('model_configurations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('model_providers', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_model_providers_provider_key'), table_name='model_providers')
    op.create_index(op.f('ix_model_providers_provider_key'), 'model_providers', ['provider_key'], unique=True)
    op.alter_column('prompt_versions', 'created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('prompt_versions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('requests', 'student_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('requests', 'prompt_version_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('requests', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('uq_requests_student_idempotency'), table_name='requests')
    op.create_unique_constraint('uq_request_student_idempotency', 'requests', ['student_id', 'idempotency_key'])
    op.alter_column('routing_rules', 'primary_model_configuration_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('routing_rules', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('source_records', 'deliverable_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('source_records', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('students', sa.Column('referral_code', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('referred_by_user_id', sa.UUID(), nullable=True))
    op.add_column('students', sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('students', sa.Column('premium_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('students', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('students', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('students', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    op.alter_column('students', 'credit_balance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text("'100.0'"))
    op.alter_column('students', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.drop_index(op.f('ix_students_external_auth_id'), table_name='students')
    op.create_index(op.f('ix_students_external_auth_id'), 'students', ['external_auth_id'], unique=True)
    op.create_index(op.f('ix_students_referral_code'), 'students', ['referral_code'], unique=True)
    op.create_index(op.f('ix_students_referred_by_user_id'), 'students', ['referred_by_user_id'], unique=False)
    op.create_foreign_key(None, 'students', 'students', ['referred_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_index(op.f('ix_students_referred_by_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_referral_code'), table_name='students')
    op.drop_index(op.f('ix_students_external_auth_id'), table_name='students')
    op.create_index(op.f('ix_students_external_auth_id'), 'students', ['external_auth_id'], unique=False)
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=False)
    op.alter_column('students', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('students', 'credit_balance',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False,
               existing_server_default=sa.text("'100.0'"))
    op.drop_column('students', 'last_login_ip')
    op.drop_column('students', 'locked_until')
    op.drop_column('students', 'failed_login_attempts')
    op.drop_column('students', 'premium_expires_at')
    op.drop_column('students', 'is_premium')
    op.drop_column('students', 'referred_by_user_id')
    op.drop_column('students', 'referral_code')
    op.alter_column('source_records', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('source_records', 'deliverable_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('routing_rules', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('routing_rules', 'primary_model_configuration_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_constraint('uq_request_student_idempotency', 'requests', type_='unique')
    op.create_index(op.f('uq_requests_student_idempotency'), 'requests', ['student_id', 'idempotency_key'], unique=1)
    op.alter_column('requests', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('requests', 'prompt_version_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('requests', 'student_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('prompt_versions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('prompt_versions', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_index(op.f('ix_model_providers_provider_key'), table_name='model_providers')
    op.create_index(op.f('ix_model_providers_provider_key'), 'model_providers', ['provider_key'], unique=False)
    op.alter_column('model_providers', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('model_configurations', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('model_configurations', 'provider_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_feature_configurations_feature_key'), table_name='feature_configurations')
    op.create_index(op.f('ix_feature_configurations_feature_key'), 'feature_configurations', ['feature_key'], unique=False)
    op.alter_column('feature_configurations', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('feature_configurations', 'active_prompt_version_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('deliverables', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('deliverables', 'student_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('deliverables', 'request_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_credit_ledger_reference_type'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_reference_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_idempotency_key'), table_name='credit_ledger')
    op.create_index(op.f('ix_credit_ledger_idempotency_key'), 'credit_ledger', ['idempotency_key'], unique=False)
    op.alter_column('credit_ledger', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('credit_ledger', 'request_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('credit_ledger', 'student_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('credit_ledger', 'description')
    op.drop_column('credit_ledger', 'reference_id')
    op.drop_column('credit_ledger', 'reference_type')
    op.drop_column('credit_ledger', 'balance_after')
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_index(op.f('ix_skill_tools_skill_id'), table_name='skill_tools')
    op.drop_table('skill_tools')
    op.drop_index(op.f('ix_reward_transactions_user_id'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_status'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_scheduled_release_at'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_referral_id'), table_name='reward_transactions')
    op.drop_table('reward_transactions')
    op.drop_index(op.f('ix_messages_skill_slug'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_index(op.f('ix_skills_preferred_provider_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_is_public'), table_name='skills')
    op.drop_index(op.f('ix_skills_is_premium'), table_name='skills')
    op.drop_index(op.f('ix_skills_fallback_provider_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referrer_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_payment_invoices_user_id'), table_name='payment_invoices')
    op.drop_index(op.f('ix_payment_invoices_status'), table_name='payment_invoices')
    op.drop_index(op.f('ix_payment_invoices_idempotency_key'), table_name='payment_invoices')
    op.drop_index(op.f('ix_payment_invoices_external_invoice_id'), table_name='payment_invoices')
    op.drop_table('payment_invoices')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_archived'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_webhook_events_provider'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_processed'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_external_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_ai_providers_slug'), table_name='ai_providers')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
